logging:
  file:
    name: ${user.home}/Registation/app-registation.log
  level:
    fr:
      afpa: info
    root: warn

registation:
  token:
    secret: azertyui #multiple 4 ? taille

spring:
 
  jpa:
    hibernate:      ddl-auto: update
       show-sql: false

  mail: 
    default-encoding: UTF-8 
    host: smtp.gmail.com 
    username: registationcdatest@gmail.com 
    password: bvrqpkjoquzrrysc #app password generated mathieu 
    port: 587 
    properties: 
      mail: 
        smtp: 
          auth: true 
          starttls: 
            enable: true
          ssl.trust: smtp.gmail.com  
    protocol: smtp 
    test-connection: false
  
# configuration spring-mvc
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
      
  datasource:    username: registation_user
    password: pwd
   
      
      profiles: 
    active:
      - dev
      
---
   
spring:  profiles: dev   
      
  datasource:
    url: jdbc:mariadb://localhost:3306/registation
    driver-class-name: org.mariadb.jdbc.Driver

---

spring:  profiles: mathieu
  
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL91Dialect
    datasource:    url: jdbc:postgresql://192.168.1.69:5432/registation
    driver-class-name: org.postgresql.Driver

---

spring:  profiles: ienien
  
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL91Dialect
  
  datasource:    url: jdbc:postgresql://IP-AURELIEN/registation
    driver-class-name: org.postgresql.Driver