logging:
  file:
    name: ${user.home}/Registation/app-registation.log
  level:
    fr:
      afpa: info
    root: warn

registation:
  token:
    secret: azertyui #multiple 4 ? taille



spring:
 


  mail: 
    default-encoding: UTF-8 
    host: smtp.gmail.com 
    username: registationcdatest@gmail.com 
    password: bvrqpkjoquzrrysc #app password generated mathieu 
    port: 587 
    properties: 
      mail: 
        smtp: 
          auth: true 
          starttls: 
            enable: true
          ssl.trust: smtp.gmail.com  
    protocol: smtp 
    test-connection: false
  
# configuration spring-mvc
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
      
  datasource:    username: registation_user
    password: pwd
   
     
      profiles: 
    active:
      - dev    
---
   
   
   
spring:  profiles: dev   
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      
      
    show-sql: false
      
  datasource:
    url: jdbc:mariadb://localhost:3306/registation
    driver-class-name: org.mariadb.jdbc.Driver

---

spring:  profiles: mathieu
    datasource:    url: jdbc:postgresql://192.168.1.69:5432/registation
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL91Dialect
      
    show-sql: false

server:
  port: 8443
  ssl:
    enabled: false  
    key-store-type: PKCS12
    key-store: registation.p12
    key-store-password: registation
    key-alias: registation
    key-password: registation
---



spring:  profiles: ienien
  
  datasource:    url: jdbc:postgresql://192.168.1.43:5432/registation
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL91Dialect
      
    show-sql: false

server:
  port: 8443
  ssl:
    enabled: false  
    key-store-type: PKCS12
    key-store: registation.p12
    key-store-password: registation
    key-alias: registation
    key-password: registation  